# Generated by Django 4.1.3 on 2023-12-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=20)),
                ('correo_empresa', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('direccion_empresa', models.CharField(max_length=255)),
                ('tipo_industria', models.CharField(max_length=255)),
                ('password', models.CharField(default=1, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas_emp',
            fields=[
                ('id_oferta_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=255)),
                ('nombre_emp', models.CharField(default='Empresa', max_length=255)),
                ('descripcion', models.TextField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupos', models.PositiveIntegerField()),
                ('fecha_limite', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('discapacidad_enfoque', models.CharField(max_length=100)),
                ('fono_empre', models.CharField(max_length=15)),
                ('correo_empre', models.EmailField(max_length=254)),
                ('id_of_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABEPD.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_postulante', models.CharField(max_length=255)),
                ('apellido_post', models.CharField(max_length=255)),
                ('telefono_postulante', models.CharField(max_length=15)),
                ('correo_postulante', models.EmailField(blank=True, max_length=254, null=True)),
                ('rut_postu', models.CharField(max_length=12, unique=True)),
                ('curriculum_postu', models.FileField(default=1, upload_to='curriculums/')),
                ('contraseña', models.CharField(default=1, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_postu', models.TextField(null=True)),
                ('fecha_creacion_postu', models.DateField(auto_now_add=True)),
                ('id_oferta_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABEPD.ofertas_emp')),
                ('id_postulante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ABEPD.postulantes')),
            ],
        ),
    ]
